### ISSUE TITLE
What is 'isLeftOverScrolled'?

### ISSUE THREAD

**Issue by HanderWei** [romandanylyk/PageIndicatorView#12]
```
private Pair<Integer, Float> getProgress(int position, float positionOffset) {
    boolean isRightOverScrolled = position > selectedPosition;
    boolean isLeftOverScrolled = position + 1 < selectedPosition;
    if (isRightOverScrolled || isLeftOverScrolled) {
        Log.d(TAG, "getProgress: " + (isRightOverScrolled ? "isRightOverScrolled" : "isLeftOverScrolled"));
        Log.d(TAG, "getProgress: " + "position :" + position + "\t selectedPosition:" + selectedPosition);
        selectedPosition = position;
    }
    ...
}
```

`isRightOverScrolled` means that scrolled to the right page.

I think `isRightOverScrolled` means scrolled to the left page.

But when I print the log, it does't show.

@romandanylyk @vdubedout Any help will be highly appreciated.

**Comment by romandanylyk** [comment]
Hi @HanderWei.
`getProgress `method has this if statetment to cover one interesting thing in `ViewPager`.
While scrolling really fast from page to page, `ViewPager `'s `positionOffset `could not be 1.0 for every scrolled page. And because I set a new selected page every time `positionOffset ` is 1.0, I need this to properly update selected page number.

So basically it is required check if `PageIndicatorView` works with a right page at the moment.
Hope it will help you to understand how it works.
Thanks.
