### ISSUE TITLE
Attributes not initialized if view created from Java

### ISSUE THREAD

**Issue by xxdavid** [romandanylyk/PageIndicatorView#16]
If you use libraries like [Anko](https://github.com/Kotlin/anko) or [Anvil](https://github.com/zserge/anvil), you create your views from Java, not XML. Often there's only the `Context` contructor used, so there are no attrs passed. In that case PageIndicatorView [calls](https://github.com/romandanylyk/PageIndicatorView/blob/master/pageindicatorview/src/main/java/com/rd/PageIndicatorView.java#L88) `init(null)`  and there's a [condition](https://github.com/romandanylyk/PageIndicatorView/blob/master/pageindicatorview/src/main/java/com/rd/PageIndicatorView.java#L855) in `initAttributes()` that won't initialize the attributes. But I don't think that's what you want. I think it should use the default attributes even if there are no passed.

Thank you for this library btw!

**Comment by romandanylyk** [comment]
Hi, I appreciate your curiosity in attributes. But I use them only to customise PageIndicatorView look, so while creating this view from constructor with out attributes, all the properties will be default (default size, AnimationType.NONE, color, etc). So while creating view via a this constructor you always will be able to call setters for those methods instead of using attributes.

Let me know if you have some other questions.
Thanks.

**Comment by romandanylyk** [comment]
Thanks for noticing, fixed in new version.

**Comment by xxdavid** [comment]
Thank you! :)
