### ISSUE TITLE
"Can't resolve symbol 'view'" when setting pageIndicatorView. 

### ISSUE THREAD

**Issue by chehanr** [romandanylyk/PageIndicatorView#22]
`    PageIndicatorView pageIndicatorView = (PageIndicatorView) view.findViewById(R.id.pageIndicatorView);
    pageIndicatorView.setViewPager(mViewPager);`

Tried re-adding support libraries but no avail. Is there a method to fix this?
Thanks in advance.

**Comment by romandanylyk** [comment]
Hi,
Can't resolve symbol 'view'
Looks like you are passing wrong parameter. Can you please specify whole code so I can take a better look what could be wrong.

Thanks

**Comment by chehanr** [comment]
```
public class PlayerActivity extends AppCompatActivity implements RadioListener {

  PlayerPagerAdapter mCustomPagerAdapter;
  ViewPager mViewPager;

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_player);

    initViews();
  }

  @SuppressWarnings("ConstantConditions")
  private void initViews() {
    PageIndicatorView pageIndicatorView = (PageIndicatorView) view
        .findViewById(R.id.pageIndicatorView);
    pageIndicatorView.setViewPager(mViewPager);

    ViewPager pager = (ViewPager) findViewById(R.id.viewPager);
    pager.setAdapter(mCustomPagerAdapter);
  }
}
```
Sorry for the late reply.

**Comment by romandanylyk** [comment]
You don't have `view` here actually. As you are working with an Activity you should simply find `PageIndicatorView` in the save way you did with `ViewPager`.
`PageIndicatorView pageIndicatorView = (PageIndicatorView) findViewById(R.id.pageIndicatorView);`

Also, you should only set `ViewPager` to `PageIndicatorView` after `ViewPager` is initialised. Instead of setting `pager` instance to ` PageIndicatorView`, you for some reason setting `mViewPager ` which is null, this is also wrong.

You adapter is also not initialised, so `ViewPager` won't work here. 
So please create adapter, then set it to `ViewPager` and then set `ViewPager` to `PageIndicatorView`.
