### ISSUE TITLE
Make setInteractiveAnimation work without setViewPager

### ISSUE THREAD

**Issue by chanonly123** [romandanylyk/PageIndicatorView#51]
Need it with infinite viewPagers and looping.

**Comment by chanonly123** [comment]
setProgress not working

**Comment by romandanylyk** [comment]
@chanonly123 Hi,
can you please describe what is your properties of `PageIndicatorView` while using `setProgress` method?
Keep in mind that using this method will only have effect while `PageIndicatorView` has `interactiveAnimation=true`, and `animationType != TYPE_NONE`, otherwise is should work as expected.

**Comment by romandanylyk** [comment]
@chanonly123 Thanks for reporting this issue.
Fixed it in `develop` branch, so it will merged to `master` and released soon.
