### ISSUE TITLE
Number Indicator inside PageIndicator

### ISSUE THREAD

**Issue by andrefpc** [romandanylyk/PageIndicatorView#85]
I'd like to insert a page number indicator inside the circles. Is it possible?

**Comment by romandanylyk** [comment]
@andrefpc, unfortunately, no, PageIndicatorView does not support this feature. 
Alternately you can implement it yourself via additional views over PageIndicatorView.

**Comment by andrefpc** [comment]
@romandanylyk I don't understand how to use this additional views..

**Comment by romandanylyk** [comment]
`ViewPager` and `PageIndicatorView` have various of callbacks, that tells you what page is currently selected, all you need to do is to listen to them and update your page number view state.

**Comment by andrefpc** [comment]
ok, i know how to get current page, but i don't understand how to update the view and insert the number inside the circleIndicator.

**Comment by romandanylyk** [comment]
@andrefpc 
Well, that depends on what you are trying to do.
If you just want to put a number over a circle indicator of `PageIndicatorView`, you will have to use `RelativeLayout` (or `ConstrainLayout`) and create several `TextViews` over `PageIndicatorView` and center them right over circle indicators. 
That's because `PageIndicatorView` does not support any kind of number indicators (only circles to indicate selected page).
